import type { ChatInteraction } from "@/lib/agent/interactions";
import { sql } from "drizzle-orm";
import { index, pgEnum, pgPolicy, pgTable, text, timestamp, uuid, jsonb } from "drizzle-orm/pg-core";
import { authUid, authenticatedRole } from "drizzle-orm/supabase";

import { profiles } from "./profiles";
import { projects } from "./projects";

export const chatRole = pgEnum("chat_role", ["user", "assistant"]);

/**
 * Agent conversation history — private to its user and scoped to a page
 * and conversation thread. The agent works in the user's draft, so the
 * conversation is theirs too.
 */
export const chatMessages = pgTable(
  "chat_messages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    pageSlug: text("page_slug").notNull(),
    /** UUID generated by the client when the user starts a fresh conversation. */
    conversationId: uuid("conversation_id").notNull(),
    role: chatRole("role").notNull(),
    content: text("content").notNull(),
    /** Optional structured UI the assistant asked the user to complete. */
    interaction: jsonb("interaction").$type<ChatInteraction | null>(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // thread list: a user's messages on a page, newest first
    index("chat_messages_history_idx").on(table.userId, table.projectId, table.pageSlug, table.createdAt),
    // one conversation, oldest first
    index("chat_messages_conversation_idx").on(table.conversationId, table.createdAt),
    pgPolicy("chat_messages_select_own", {
      for: "select",
      to: authenticatedRole,
      using: sql`${table.userId} = ${authUid}`,
    }),
    pgPolicy("chat_messages_insert_own", {
      for: "insert",
      to: authenticatedRole,
      withCheck: sql`${table.userId} = ${authUid} and public.is_project_member(${table.projectId})`,
    }),
    pgPolicy("chat_messages_delete_own", {
      for: "delete",
      to: authenticatedRole,
      using: sql`${table.userId} = ${authUid}`,
    }),
  ],
);
